Variables:

  Paths:
    TrainImagePaths:
      - /home/kevin/Documents/Kaggle/human-protein-image-classification/data/train_combined
      - /home/kevin/Documents/Kaggle/human-protein-image-classification/data/train_combined_HPAv18
    TrainLabelPaths: /home/kevin/Documents/Kaggle/human-protein-image-classification/data/train_all_no_dupes.csv

    TestImagePaths: /home/kevin/Documents/Kaggle/human-protein-image-classification/data/test_combined
    RootSavePathForTimeStampedSavePath: /media/hd/Kaggle/human-protein-image-classification/results

  Learner:
    ToFP16: true

  DataBunch:
    TrainBatchSize: 32
    ValBatchSize: 4
    TestBatchSize: 4
    NumDataBunchWorkers: 0
    SamplerFunctionName: uniform_weights

  Augmentation:
    TrainResizeHeight: 768
    TrainResizeWidth: 768
    TrainCropHeight: 512
    TrainCropWidth: 512
    TrainBrightnessTransformProb: 0.5
    TrainElasticTransformProb: 0.5
    TestResizeHeight: 768
    TestResizeWidth: 768
    FiveCropTTACropHeight: 512
    FiveCropTTACropWidth: 512

  Preprocessing:
    NormalizeMean: [12.14099732, 10.9779429,   5.46488976, 22.30204426]
    NormalizeStd: [18.48077492, 17.25324061, 13.88083803, 32.78388995]

  Training:
    TrainSamplesToUse: 100
    TestSamplesToUse: 100
    TrainingSchemeName: training_scheme_multi_step
    EpochsForStepForHyperparameters: [[0, 25, 30, 35, 40]]
    HyperparameterValues: [[30e-5, 15e-5, 7.5e-5, 3e-5, 1e-5]]
    HyperparameterNames: ["lr"]
    EndEpoch: 1

  Model:
    Name: densenet121_four_channel_input_two_fc
    Pretrained: True
    fc1_bias: false
    fc1_dropout: 0.5
    fc1_out: 512
    fc2_bias: false
    fc2_dropout: 0.5
    fc2_out: 28

  Inference:
    RelativeModelSavePath: null
    LocalRootSavePath: null
    DockerRootSavePath: /app/model_artifacts

Resources:
  Data:
    Loading:
      LoadTestingData:
        properties:
          pointer: load_testing_data
          arguments:
            root_image_paths: !Var Paths.TestImagePaths
            use_n_samples: !Var Training.TestSamplesToUse
          output_names:
            - test_X

      LoadTrainingData:
        properties:
          pointer: load_training_data
          arguments:
            root_image_paths: !Var Paths.TrainImagePaths
            root_label_paths: !Var Paths.TrainLabelPaths
            use_n_samples: !Var Training.TrainSamplesToUse
          output_names:
            - train_X
            - train_y
            - train_y_one_hot
    Dataset:
      CreateTrainingDataset:
        properties:
          output_names:
            - TrainingDataset
          partial: true
          arguments:
            augment_fn: !Ref CreateAugmentationFunction.AugmentationFunction
            open_image_fn: !Ref CreateOpenImageFunction.OpenImageFunction
            normalize_fn: !Ref CreateNormalizeFunction.NormalizeFunction
          pointer: ProteinClassificationDataset

      CreateValidationDataset:
        properties:
          pointer: ProteinClassificationDataset
          partial: true
          arguments:
            augment_fn: !Ref CreateTestAugmentationFunction.TestAugmentationFunction
            open_image_fn: !Ref CreateOpenImageFunction.OpenImageFunction
            normalize_fn: !Ref CreateNormalizeFunction.NormalizeFunction
            tta_fn: !Ref CreateFiveCropTTAFunction.FiveCropTTAFunction
          output_names:
            - ValidationDataset

      CreateTestingDataset:
        properties:
          pointer: ProteinClassificationDataset
          partial: true
          arguments:
            augment_fn: !Ref CreateTestAugmentationFunction.TestAugmentationFunction
            open_image_fn: !Ref CreateOpenImageFunction.OpenImageFunction
            normalize_fn: !Ref CreateNormalizeFunction.NormalizeFunction
            tta_fn: !Ref CreateFiveCropTTAFunction.FiveCropTTAFunction
          output_names:
            - TestingDataset

      CreateDataBunch:
        properties:
          pointer: create_data_bunch
          partial: true
          arguments:
            train_X: !Ref LoadTrainingData.train_X
            train_y_one_hot: !Ref LoadTrainingData.train_y_one_hot
            train_y: !Ref LoadTrainingData.train_y
            test_X: !Ref LoadTestingData.test_X
            train_bs: !Var DataBunch.TrainBatchSize
            test_bs: !Var DataBunch.ValBatchSize
            val_bs: !Var DataBunch.TestBatchSize
            train_ds: !Ref CreateTrainingDataset.TrainingDataset
            val_ds: !Ref CreateValidationDataset.ValidationDataset
            test_ds: !Ref CreateTestingDataset.TestingDataset
            sampler: !Ref CreateSampler.Sampler
            num_workers: !Var DataBunch.NumDataBunchWorkers
          output_names:
            - DataBunch
    Sampling:
      CreateSamplerFunction:
        properties:
          pointer: !Var DataBunch.SamplerFunctionName
          partial: true
          output_names:
            - SamplerFunction

      CreateSampler:
        properties:
          pointer: create_sampler
          arguments:
            sampler_fn: !Ref CreateSamplerFunction.SamplerFunction
          partial: true
          output_names:
            - Sampler

      CreateSplitIndices:
        properties:
          pointer: create_split_indices
          arguments:
            data_splitter: !Ref CreateDataSplitter.DataSplitter
            X: !Ref LoadTrainingData.train_X
            y: !Ref LoadTrainingData.train_y_one_hot
          output_names:
            - SplitIndices

      CreateDataSplitter:
        properties:
          pointer: MultilabelStratifiedShuffleSplit
          arguments:
            n_splits: 1
            test_size: 0.2
            random_state: 6969
          output_names:
            - DataSplitter
  Image:
    Loading:
      CreateOpenImageFunction:
        properties:
          pointer: open_numpy
          arguments:
            with_image_wrapper: true
          partial: true
          output_names:
            - OpenImageFunction

    Augmentation:
      CreateAugmentationFunction:
        properties:
          pointer: crop_rotate90_flip_brightness_elastic
          arguments:
            height: !Var Augmentation.TrainResizeHeight
            width: !Var Augmentation.TrainResizeWidth
            crop_height: !Var Augmentation.TrainCropHeight
            crop_width: !Var Augmentation.TrainCropWidth
            brightness_transform_p: !Var Augmentation.TrainBrightnessTransformProb
            elastic_transform_p: !Var Augmentation.TrainElasticTransformProb
            with_image_wrapper: true
          output_names:
            - AugmentationFunction
      #      CreateAugmentationFunction:
      #        properties:
      #          pointer: random_crop_flip_shift_scale_rotate_brightness_contrast_cutout
      #          arguments:
      #            height: !Var TrainResizeHeight
      #            width: !Var TrainResizeWidth
      #            crop_height: !Var TrainCropHeight
      #            crop_width: !Var TrainCropWidth
      #            cutout_height: !Var TrainCutoutHeight
      #            cutout_width: !Var TrainCutoutWidth
      #            with_image_wrapper: true
      #          output_names:
      #            - AugmentationFunction
      CreateTestAugmentationFunction:
        properties:
          pointer: resize_aug
          arguments:
            height: !Var Augmentation.TestResizeHeight
            width: !Var Augmentation.TestResizeWidth
            with_image_wrapper: true
          output_names:
            - TestAugmentationFunction

      CreateFiveCropTTAFunction:
        properties:
          pointer: five_crop_tta_transform
          partial: true
          arguments:
            crop_height: !Var Augmentation.FiveCropTTACropHeight
            crop_width: !Var Augmentation.FiveCropTTACropWidth
          output_names:
            - FiveCropTTAFunction
    Preprocessing:
      #      CalculateMeanAndStdForDataset:
      #        properties:
      #          pointer: calculate_mean_and_std_for_dataset
      #          arguments:
      #            data_paths:
      #              - !Ref LoadTrainingData.train_X
      #              - !Ref LoadTestingData.test_X
      #          output_names:
      #            - mean
      #            - std

      CreateNormalizeFunction:
        properties:
          pointer: normalize
          arguments:
            mean: !Var Preprocessing.NormalizeMean
            std: !Var Preprocessing.NormalizeStd
          partial: true
          output_names:
            - NormalizeFunction

      CreateDenormalizeFunction:
        properties:
          pointer: denormalize
          arguments:
            mean: !Var Preprocessing.NormalizeMean
            std: !Var Preprocessing.NormalizeStd
          partial: true
          output_names:
            - DenormalizeFunction

    RunTrainingLoop:
      properties:
        pointer: training_loop
        arguments:
          create_learner: !Ref CreateLearner.LearnerCreator
          data_bunch_creator: !Ref CreateDataBunch.DataBunch
          config_saver: !Ref SaveConfiguration.ConfigSaver
          split_indices: !Ref CreateSplitIndices.SplitIndices
          training_scheme: !Ref CreateTrainingScheme.TrainingScheme
          record_results: !Ref RunRecordResults.ResultRecorder

    CreateTrainingScheme:
      properties:
        pointer: !Var Training.TrainingSchemeName
        arguments:
          epochs_for_step_for_hyperparameters: !Var Training.EpochsForStepForHyperparameters
          hyperparameter_values: !Var Training.HyperparameterValues
          hyperparameter_names: !Var Training.HyperparameterNames
          end_epoch: !Var Training.EndEpoch
        partial: true
        output_names:
          - TrainingScheme

    #    CreateTrainingScheme:
    #      properties:
    #        pointer: !Var CreateTrainingScheme.TrainingSchemeName
    #        arguments:
    #          lr: !Var CreateTrainingScheme.LearningRate
    #          epochs: !Var CreateTrainingScheme.Epochs
    #        partial: true
    #        output_names:
    #          - TrainingScheme

    CreateLearner:
      properties:
        pointer: create_learner
        partial: true
        arguments:
          model_creator: !Ref CreateModel.Model
          metrics:
            - !Ref CreateAccuracyMetric.AccuracyMetric
            - !Ref CreateF1SoftMetric.F1SoftMetric
            - !Ref CreateFocalLossMetric.FocalLossMetric
          loss_funcs:
            - !Ref CreateLovaszHingeFlatLoss.LovaszHingeFlatLoss
            #              - !Ref CreateSoftF1Loss.SoftF1Loss
            - !Ref CreateFocalLoss.FocalLoss
          callbacks_creator: !Ref CreateCallbacks.CallbacksCreator
          callback_fns_creator: !Ref CreateLearnerCallbacks.LearnerCallbacksCreator
          to_fp16: !Var Learner.ToFP16
        output_names:
          - LearnerCreator

    CreateModel:
      properties:
        pointer: !Var Model.Name
        arguments:
          pretrained: !Var Model.Pretrained
          fc1_bias: !Var Model.fc1_bias
          fc1_dropout: !Var Model.fc1_dropout
          fc1_out: !Var Model.fc1_out
          fc2_bias: !Var Model.fc2_bias
          fc2_dropout: !Var Model.fc2_dropout
          fc2_out: !Var Model.fc2_out
        partial: true
        output_names:
          - Model

    Metric:
      CreateAccuracyMetric:
        properties:
          pointer: accuracy
          partial: true
          output_names:
            - AccuracyMetric

      CreateF1SoftMetric:
        properties:
          pointer: f1_soft
          partial: true
          output_names:
            - F1SoftMetric

      CreateFocalLossMetric:
        properties:
          pointer: focal_loss
          partial: true
          arguments:
            gamma: 2
          output_names:
            - FocalLossMetric

    Loss:
      CreateFocalLoss:
        properties:
          pointer: FocalLoss
          arguments:
            gamma: 2
          output_names:
            - FocalLoss

      CreateSoftF1Loss:
        properties:
          pointer: SoftF1Loss
          output_names:
            - SoftF1Loss

      CreateLovaszHingeFlatLoss:
        properties:
          pointer: LovaszHingeFlatLoss
          output_names:
            - LovaszHingeFlatLoss

  Callbacks:
    CreateCallbacks:
      properties:
        pointer: create_callbacks
        partial: true
        arguments:
          callback_references:
            - !Ref CreateLabelExtractorCallback.LabelExtractorCallback
            - !Ref CreateFiveCropTTAPredictionCallback.FiveCropTTAPredictionCallback
        output_names:
          - CallbacksCreator

    CreateLearnerCallbacks:
      properties:
        pointer: create_learner_callbacks
        partial: true
        arguments:
          learner_callback_references:
            - !Ref CreateCSVLoggerLearnerCallback.CSVLoggerLearnerCallback
            - !Ref CreateOutputRecorderLearnerCallback.OutputRecorderLearnerCallback
            - !Ref CreateGradientClippingLearnerCallback.GradientClippingLearnerCallback
            - !Ref CreateSaveModelCallback.SaveModelCallback
            - !Ref CreateTensorBoardRecorderLearnerCallback.TensorBoardRecorder
        output_names:
          - LearnerCallbacksCreator

    CreateLabelExtractorCallback:
      properties:
        pointer: LabelExtractorCallback
        partial: true
        output_names:
          - LabelExtractorCallback

    CreateSaveModelCallback:
      properties:
        pointer: SaveModelCallback
        arguments:
          monitor: "VAL/focal_loss"
          save_path_creator: !Ref CreateTimeStampedSavePath.SavePathCreator
        partial: true
        output_names:
          - SaveModelCallback


    CreateCSVLoggerLearnerCallback:
      properties:
        pointer: create_csv_logger
        partial: true
        arguments:
          save_path_creator: !Ref CreateTimeStampedSavePath.SavePathCreator
        output_names:
          - CSVLoggerLearnerCallback

    CreateTensorBoardRecorderLearnerCallback:
      properties:
        pointer: TensorBoardRecorder
        partial: true
        arguments:
          save_path_creator: !Ref CreateTimeStampedSavePath.SavePathCreator
        output_names:
          - TensorBoardRecorder

    CreateOutputRecorderLearnerCallback:
      properties:
        pointer: create_output_recorder
        partial: true
        arguments:
          save_path_creator: !Ref CreateTimeStampedSavePath.SavePathCreator
          denormalize_fn: !Ref CreateDenormalizeFunction.DenormalizeFunction
        output_names:
          - OutputRecorderLearnerCallback

    CreateGradientClippingLearnerCallback:
      properties:
        pointer: GradientClipping
        partial: true
        arguments:
          clip: 1.0
        output_names:
          - GradientClippingLearnerCallback

    CreateFiveCropTTAPredictionCallback:
      properties:
        pointer: FiveCropTTAPredictionCallback
        arguments:
          aggregate_mode: MAX
        output_names:
          - FiveCropTTAPredictionCallback


  Output:
    CreateTimeStampedSavePath:
      properties:
        pointer: create_time_stamped_save_path
        partial: true
        arguments:
          save_path: !Var Paths.RootSavePathForTimeStampedSavePath
        output_names:
          - SavePathCreator

    SaveConfiguration:
      properties:
        pointer: save_config
        arguments:
          save_path_creator: !Ref CreateTimeStampedSavePath.SavePathCreator
        partial: true
        output_names:
          - ConfigSaver

    CreateResultRecorder:
      properties:
        pointer: ResultRecorder
        partial: true
        output_names:
          - ResultRecorderCreator

    RunRecordResults:
      properties:
        pointer: record_results
        arguments:
          result_recorder_callback: !Ref CreateResultRecorder.ResultRecorderCreator
          save_path_creator: !Ref CreateTimeStampedSavePath.SavePathCreator
        partial: true
        output_names:
          - ResultRecorder


  Inference:
    CheckIfRunInferenceModelSavePath:
      properties:
        pointer: check_if_run_inference_model_save_path
        arguments:
          relative_model_save_path: !Var Inference.RelativeModelSavePath
          local_root_save_path: !Var Inference.LocalRootSavePath
          docker_root_save_path: !Var Inference.DockerRootSavePath
        output_names:
          - ShouldRun

    CreateInferenceModelSavePath:
      properties:
        pointer: create_inference_model_save_path
        should_run: !Ref CheckIfRunInferenceModelSavePath.ShouldRun
        arguments:
          relative_model_save_path: !Var Inference.RelativeModelSavePath
          local_root_save_path: !Var Inference.LocalRootSavePath
          docker_root_save_path: !Var Inference.DockerRootSavePath
        output_names:
          - Path

    CreateLearnerForInference:
      properties:
        pointer: create_learner
        partial: true
        arguments:
          model_creator: !Ref CreateModel.Model
          metrics:
            - !Ref CreateAccuracyMetric.AccuracyMetric
            - !Ref CreateF1SoftMetric.F1SoftMetric
          loss_funcs:
            - !Ref CreateLovaszHingeFlatLoss.LovaszHingeFlatLoss
            - !Ref CreateFocalLoss.FocalLoss
          callbacks_creator: !Ref CreateCallbacksForInference.CallbacksCreator
          to_fp16: true
          model_path: !Ref CreateInferenceModelSavePath.Path
        output_names:
          - LearnerCreator

    CreateCallbacksForInference:
      properties:
        pointer: create_callbacks
        partial: true
        arguments:
          callback_references:
            - !Ref CreateLabelExtractorCallback.LabelExtractorCallback
            - !Ref CreateFiveCropTTAPredictionCallback.FiveCropTTAPredictionCallback
        output_names:
          - CallbacksCreator

    CreateDataBunchForInference:
      properties:
        pointer: create_data_bunch_for_inference
        arguments:
          ds: !Ref CreateTestingDataset.TestingDataset
          num_workers: 0
        partial: true
        output_names:
          - DataBunchCreator

    CreateInference:
      properties:
        pointer: create_inference
        partial: true
        arguments:
          inference_data_bunch_creator: !Ref CreateDataBunchForInference.DataBunchCreator
          inference_learner_creator: !Ref CreateLearnerForInference.LearnerCreator
          result_recorder_callback: !Ref CreateResultRecorder.ResultRecorderCreator
        output_names:
          - Inference

